# -*- coding: utf-8 -*-
"""updatedatabase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19w_W_vKPGE72gnyXnUxDYuxcOd3Ur8gS
"""

import os
import pandas as pd
# path = '/content/drive/MyDrive/Colab Notebooks/FinanceiroPessoal/extratos/'
# root = '/content/drive/MyDrive/Colab Notebooks/FinanceiroPessoal/'

root = os.getcwd()
path = root+'/extratos/'

# Iterate through all files in the folder
for filename in os.listdir(path):
    # Check if the file is not a .csv file
    if not filename.endswith(".csv"):
        # Construct the full file path
        file_path = os.path.join(path, filename)
        # Delete the file
        os.remove(file_path)

# prompt: insert on list every file on path that ends with .csv
csv_files = [f for f in os.listdir(path) if f.endswith('.csv')]

alldata = pd.DataFrame()
for file in csv_files:
  df = pd.read_csv(path+file)
  alldata = pd.concat([alldata,df])

def check_if_str(string, substring_array):
  for substring in substring_array:
    if substring in string:
      return True
  return False

doacao_texto = ['GREG', 'CARLOS JOSE','LUCAS GONCALVES','LBV','GACC','MAILSON',"CRISTO"]
resgate_texto = ['JOAO PEDRO','RESGATE','NUINVEST','CRIPTO',"FORIS","LATAM GATEWAY"]
aplicacao_texto = ["JOAO PEDRO",'APLICAÇÃO','CRIPTO',"FORIS","LATAM GATEWAY"]

alldata['Descrição'] = alldata['Descrição'].str.upper()

alldata['Tipo'] = ''
alldata['Tipo'] = alldata.apply(lambda row: 'Outros Recebimentos' if (float(row['Valor'])>0) else row['Tipo'], axis=1)
alldata['Tipo'] = alldata.apply(lambda row: 'Salário' if ('CLINSERVICE' in row['Descrição']) else row['Tipo'], axis=1)
alldata['Tipo'] = alldata.apply(lambda row: 'Gasto' if (float(row['Valor'])<0) else row['Tipo'], axis=1)
alldata['Tipo'] = alldata.apply(lambda row: 'Gasto Crédito' if ('FATURA' in row['Descrição']) else row['Tipo'], axis=1)
alldata['Tipo'] = alldata.apply(lambda row: 'Resgate Investimento' if check_if_str(row['Descrição'],resgate_texto) and float(row['Valor'])>0 else row['Tipo'], axis=1)
alldata['Tipo'] = alldata.apply(lambda row: 'Aplicação Investimento' if check_if_str(row['Descrição'],aplicacao_texto) and float(row['Valor'])<0 else row['Tipo'], axis=1)
alldata['Tipo'] = alldata.apply(lambda row: 'Doação' if check_if_str(row['Descrição'], doacao_texto) and float(row['Valor'])<0 else row['Tipo'], axis=1)

alldata['Categoria'] = ''
map = {'Outros Recebimentos':'Recebido',
       'Salário':'Recebido',
       'Gasto': 'Gastos',
       'Gasto Crédito': "Gastos",
       'Resgate Investimento': "Investimento",
       'Aplicação Investimento': "Investimento",
       'Doação': "Doação"
       }

alldata["Categoria"] = alldata["Tipo"].map(map)

alldata['Valor'] = alldata['Valor'].astype(str)
alldata['Valor'] = alldata['Valor'].str.replace('.',',')


alldata.to_csv(root+'alldata.csv',index=False, sep=';')